# Generated by Django 4.0.5 on 2022-06-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0007_alter_post_mainphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='photo',
        ),
    ]
