# Generated by Django 4.0.5 on 2022-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0008_rename_mainphoto_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
    ]
