# Generated by Django 4.0.5 on 2022-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0009_post_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shirt_size',
            field=models.CharField(choices=[('D', 'Dresses'), ('M', 'Blouses & Shirts'), ('C', 'Coats'), ('B', 'Bombers'), ('T', 'T-shirts & Sweaters'), ('S', 'Sweatshirts'), ('Car', 'Cardigans & Sweaters'), ('J', 'Jackets'), ('T', 'Trousers'), ('Je', 'Jeans'), ('S', 'Shorts')], default='', max_length=20),
        ),
    ]
